[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Velocidad del monitor serie (para que no salgan símbolos raros)
monitor_speed = 115200

; Aquí se instalan las librerías externas
lib_deps =
    knolleary/PubSubClient @ ^2.8
    ; Las librerías WiFi, HTTPClient y WiFiClientSecure ya vienen integradas en el framework